server:
  port: 3003

spring:
  datasource:
    url: jdbc:sqlite:/Users/unblockd/unblockd_workspaces/old-onerepo/backends/bun-sqlite/gtd.db
    driver-class-name: org.sqlite.JDBC
    # We do not use JPA here, but Spring Data JDBC
